"""Generate the FULL categorized emoji dataset (dock/emoji_data.py) from Unicode's
emoji-test.txt — the same set Windows' emoji panel uses.

Keeps every fully-qualified emoji, grouped by the official Unicode groups, skips
skin-tone variants (shown via a tone toggle, not 5x in the grid) and the Component
group. Merges in the previously-curated keywords for richer search where available.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "tools", "emoji-test.txt")
OUT = os.path.join(ROOT, "dock", "emoji_data.py")

GROUP_MAP = {
    "Smileys & Emotion": ("smileys", "Smileys & Emotion", "😀"),
    "People & Body": ("people", "People & Body", "👋"),
    "Animals & Nature": ("animals", "Animals & Nature", "🐻"),
    "Food & Drink": ("food", "Food & Drink", "🍕"),
    "Travel & Places": ("travel", "Travel & Places", "✈️"),
    "Activities": ("activities", "Activities", "⚽"),
    "Objects": ("objects", "Objects", "💡"),
    "Symbols": ("symbols", "Symbols", "❤️"),
    "Flags": ("flags", "Flags", "🏳️"),
}
SKIN = set(range(0x1F3FB, 0x1F400))
_NAME_RE = re.compile(r"^\S+\s+E[\d.]+\s+(.*)$")

# enrich search with the previously-curated keywords (best effort)
kw = {}
try:
    sys.path.insert(0, ROOT)
    from dock.emoji_data import CATEGORIES as OLD
    for c in OLD:
        for ch, _name, terms in c["emoji"]:
            kw[ch] = terms
except Exception:
    pass

cats, order = {}, []
cur_group = None
seen = set()
with open(SRC, encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n")
        if line.startswith("# group:"):
            cur_group = line.split(":", 1)[1].strip()
            continue
        if not line or line.startswith("#") or ";" not in line or "#" not in line:
            continue
        cps_part, rest = line.split(";", 1)
        status = rest.split("#", 1)[0].strip()
        if status != "fully-qualified":
            continue
        gm = GROUP_MAP.get(cur_group)
        if gm is None:
            continue
        cps = [int(x, 16) for x in cps_part.strip().split()]
        if any(cp in SKIN for cp in cps):
            continue
        ch = "".join(chr(cp) for cp in cps)
        if ch in seen:
            continue
        seen.add(ch)
        comment = rest.split("#", 1)[1].strip()
        m = _NAME_RE.match(comment)
        name = (m.group(1) if m else comment).strip().lower()
        if name.startswith("flag: "):
            name = name[6:]
        key, label, icon = gm
        if key not in cats:
            cats[key] = {"label": label, "icon": icon, "emoji": []}
            order.append(key)
        terms = name
        if kw.get(ch):
            words = []
            for w in (name + " " + kw[ch]).split():
                if w not in words:
                    words.append(w)
            terms = " ".join(words)
        cats[key]["emoji"].append((ch, name, terms))

lines = ['"""Categorized emoji dataset for the emoji picker — the full Unicode set,',
         'auto-generated by tools/gen_emoji_full.py from Unicode emoji-test.txt. Do not edit."""',
         "",
         "CATEGORIES = ["]
for key in order:
    c = cats[key]
    lines.append("    {")
    lines.append(f"        \"key\": {key!r}, \"label\": {c['label']!r}, \"icon\": {c['icon']!r},")
    lines.append("        \"emoji\": [")
    for ch, name, terms in c["emoji"]:
        lines.append(f"            ({ch!r}, {name!r}, {terms!r}),")
    lines.append("        ],")
    lines.append("    },")
lines.append("]")
lines.append("")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

total = sum(len(cats[k]["emoji"]) for k in order)
print(f"wrote {OUT}")
print(f"categories: {len(order)} · emoji: {total}")
for k in order:
    print(f"  {k:<12} {len(cats[k]['emoji']):>4}")
