"""Turn the curate-emoji-dataset workflow output into dock/emoji_data.py.

Validates every emoji codepoint (drops unnamed / tofu glyphs), dedupes, and writes
a clean categorized module: CATEGORIES = [{key,label,icon,emoji:[(char,name,search)]}].
"""
import html
import json
import os
import sys
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dock", "emoji_data.py")

src = sys.argv[1] if len(sys.argv) > 1 else None
if not src or not os.path.exists(src):
    print("usage: gen_emoji_data.py <workflow-output.json>")
    sys.exit(2)

with open(src, "r", encoding="utf-8") as f:
    obj = json.load(f)
data = obj.get("result", obj)
cats_in = data["categories"]

# codepoints that are legal inside an emoji sequence but have no standalone name
SAFE = {0x200D, 0xFE0F, 0xFE0E, 0x20E3, 0xE0067, 0xE006C, 0xE0062, 0xE0073, 0xE0077,
        0xE006E, 0xE007F}  # ZWJ, VS15/16, keycap, tag chars (subdivision flags)
SKIN = set(range(0x1F3FB, 0x1F400))


def valid(ch: str) -> bool:
    if not ch:
        return False
    for c in ch:
        cp = ord(c)
        if cp in SAFE or cp in SKIN or 0xE0061 <= cp <= 0xE007A:
            continue
        try:
            unicodedata.name(c)
        except ValueError:
            return False
    return True


def search_terms(name: str, keywords) -> str:
    words = []
    for tok in (name or "").split() + list(keywords or []):
        w = str(tok).lower().strip()
        for piece in w.replace("/", " ").split():
            if piece and piece not in words:
                words.append(piece)
    return " ".join(words)


seen = set()
cats_out = []
dropped = 0
for c in cats_in:
    items = []
    for e in c.get("emoji", []):
        ch = (e.get("char") or "").strip()
        if not ch or ch in seen:
            continue
        if not valid(ch):
            dropped += 1
            continue
        seen.add(ch)
        items.append((ch, (e.get("name") or "").strip().lower(),
                      search_terms(e.get("name"), e.get("keywords"))))
    cats_out.append((c["key"], html.unescape(c["label"]), c["icon"], items))

lines = ['"""Categorized emoji dataset for the emoji picker — auto-generated by',
         'tools/gen_emoji_data.py from the curate-emoji-dataset workflow. Do not edit by hand."""',
         "",
         "CATEGORIES = ["]
for key, label, icon, items in cats_out:
    lines.append("    {")
    lines.append(f"        \"key\": {key!r}, \"label\": {label!r}, \"icon\": {icon!r},")
    lines.append("        \"emoji\": [")
    for ch, name, terms in items:
        lines.append(f"            ({ch!r}, {name!r}, {terms!r}),")
    lines.append("        ],")
    lines.append("    },")
lines.append("]")
lines.append("")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

total = sum(len(items) for *_, items in cats_out)
print(f"wrote {OUT}")
print(f"categories: {len(cats_out)} · emoji: {total} · dropped(invalid): {dropped}")
for key, label, icon, items in cats_out:
    print(f"  {key:<12} {len(items):>4}")
